travis:
  secure:
    BINSTAR_TOKEN: 1GzLCordKsQHzGXOPN15Gita7GvBU6TgyNjJz/7Gw9829e51Y1UEYHuMYKDrVHbqUX22PJ4XSGsrj2jQw2JawwnNACR+/XZN6lZyxUvpt8pVnniyQgzqcbc7cDxo1VtjRUv0iT0pbDfTg2rPMLrtvhDnbCUvwB7OnTj8amSXFPoipS0dNM/QP1rGPb0eJUef+sXBykoW2OvTw2qEhuJ3E0EkschxMYmW+GsLKjXXd22H34S9TWS3IeYnhQ8ye6HQO/rqri57ZWPDYxJZYVvyocdBLr6JsOy/oc2GJb+4sHXzZ3+3sB00dQhfc0Mfjc0CNR0VckEp2pD4LexoDPsJ2UB6YwmJSVGaw6/TrK6ZC5X/hejaru6N3QFgVx9LRnYXS1Y2IDQT9prwE9xI9WQnan7Jbkws/ZGVHvKzvrr5qfu3ZNgnJo6NGu6lDXqy5uVeq5nCv5su3PJEwL8suxJOJHaQMkWBmZevq14glCdd9+n1J76zJyPsMoPYmKX77geOQA+z7BcrB26SJqoYBXxskUeIccYcrGIt9bqOCBsjowcP6506yjjSrY1d5chBjkJRmz00MXQ9nxkxO00saR0HcP/c5sL6fp64HIBAh7T/xppzTIu/1sYXiZRf4YQ04EDZsbUUxe6XSn3txr5jkFtkPZ8t6eNVZRtFE4yJCN8Ylwc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
